version: '3.4'

services:
  rabbit:
    image: rabbitmq:3.8.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - 5672:5672
      - 8080:15672